### PR TITLE
Le res

### PR DESCRIPTION
**Pull request by donlinglok1**

### CODE REVIEW

**Comment by AugmentedRealityCat** [comment]
Is the LeRes code now included in the master branch ?

**Comment by donlinglok1** [comment]
> Is the LeRes code now included in the master branch ?

no, I will keep 2 versions separately since the original project is designed to use Midas, and I think the 3d result of Midas is better than LeRes? (although i only tested a few images)

The main branch will be Midas and the LeRes branch for LeRes.

**Comment by AugmentedRealityCat** [comment]
I see, it became a branch on the original project, and this branch over here was for your own repo.
So now the proper LeRes version of the project would be this one ?
https://github.com/vt-vl-lab/3d-photo-inpainting/pull/188

**Comment by donlinglok1** [comment]
> > Is the LeRes code now included in the master branch ?
> 
> no, I will keep 2 versions separately since the original project is designed to use Midas, and I think the 3d result of Midas is better than LeRes? (although i only tested a few images)
> 
> The main branch will be Midas and the LeRes branch for LeRes.

I don’t think they will update the original repo any more, but I also find some interesting issues here,

https://github.com/vt-vl-lab/3d-photo-inpainting/issues/136

**Comment by AugmentedRealityCat** [comment]
> I think the 3d result of Midas is better than LeRes?

Definitely NOT.
LeRes is much better. Much more detailed, much more accurate. It's better in every way.

EDIT: look at this ! This is LeRes. Do you have any result from Midas that are looking as good as that that I may have missed somehow ? It is way better than anything else I've tested so far.
https://user-images.githubusercontent.com/114955776/204782473-18ebe02c-1c1a-430c-863c-d85260f0dd49.png

**Comment by donlinglok1** [comment]
> > I think the 3d result of Midas is better than LeRes?
> 
> Definitely NOT. LeRes is much better. Much more detailed, much more accurate. It's better in every way.
> 
> EDIT: look at this ! This is LeRes. Do you have any result from Midas that are looking as good as that that I may have missed somehow ? It is way better than anything else I've tested so far. https://user-images.githubusercontent.com/114955776/204782473-18ebe02c-1c1a-430c-863c-d85260f0dd49.png

I see your point, let's merge the LeRes to the master branch and I will create a MiDas branch for backup.

**Comment by AugmentedRealityCat** [comment]
> I also find some interesting issues here,
> [vt-vl-lab#136](https://github.com/vt-vl-lab/3d-photo-inpainting/issues/136)

Do you think we can use that to make your code work even better ? 
Honestly, it's already very impressive ! Thank you so much once again for your time and your efforts to make this happen.

**Comment by donlinglok1** [comment]
> > I also find some interesting issues here,
> > [vt-vl-lab#136](https://github.com/vt-vl-lab/3d-photo-inpainting/issues/136)
> 
> Do you think we can use that to make your code work even better ? Honestly, it's already very impressive ! Thank you so much once again for your time and your efforts to make this happen.

I have tested the code form https://github.com/vt-vl-lab/3d-photo-inpainting/issues/136

https://github.com/donlinglok/3d-photo-inpainting/tree/test

seem the result are the same. so I guess the current change in the master is the best we can do.

**Comment by AugmentedRealityCat** [comment]
What are your intentions with this project ? Do you still want to turn it into an extension for Automatic1111 ? If you need a beta tester, I'll be there for you.

**Comment by donlinglok1** [comment]
Thank you for the support

I am just interested in the [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and would like to see if there is any fun and cool technology. So this repo only shares a demo for fun outputs, I didn't have the skill set to build the AI from the beginning yet.

For the extension, I can see there is already some good extension basic on the depth image tech, we will witness how great things happen. https://github.com/Extraltodeus/depthmap2mask/issues/11

**Comment by AugmentedRealityCat** [comment]
There is also another project about normal maps, and the one that creates masks from depthmaps. 
Maybe you should all get together to produce a new **3D** tab for Automatic1111 WebUI ! That would be tremendously popular among users I am sure.

**Comment by donlinglok1** [comment]
cool, where is the normal maps repo?

I have also changed the name of the idea request to "3D video/gif" https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4268

**Comment by AugmentedRealityCat** [comment]
> cool, where is the normal maps repo?

Over here:
https://github.com/graemeniedermayer/stable-diffusion-webui-normalmap-script

**Comment by AugmentedRealityCat** [comment]
You might want to have a look at this as well:
https://depthplayer.ugocapeto.com/

It's an online player that creates a 3d model from an image + a depthmap. You can then download it as an OBJ, and you can also adjust some parameters, like mesh smoothing and downsampling.

There is more info here: https://3dstereophoto.blogspot.com/2019/01/depthplayerugocapetocom-web-tool-to.html
and they have a repo over here: https://github.com/spite/depth-player

**Comment by donlinglok1** [comment]
I see, gen-ing 3D model,

speaking of this, you may try on this, 
https://colab.research.google.com/drive/16R6Mwi4lmzdzZDVsF1NdqBX1ScIdU8nW?usp=sharing

The repo is here: https://github.com/nv-tlabs/GET3D

**Comment by AugmentedRealityCat** [comment]
The big advantage of the link I provided is that it produces a 3d object with UV coordinates, and it does it in OBJ format. It also has a few adjustment parameters that could be useful if you don't use a 3d app after (I had to because I wanted to export an FBX for a specific engine). 
But other than that the 3d photo inpainting algo you adapted for windows should provide better 3d results in my opinion. The inpainting should make a difference.

Also, after testing multiple algorythms, I feel that LeRes is best for things like normal maps where local details are more important, and that for 3d extraction where accurate distances are important, Midas-21 in multi-resolution mode provides the best results. I'll keep on testing as this is all quite preliminary.

**Comment by AugmentedRealityCat** [comment]
Testing an HTML embedding of a 3d model to see it it works (if it's a problem just delete - this is not important)

https://meshvalley.com/embed/6391b4d1fb93daaa5e90289a?play&nofx

**Comment by donlinglok1** [comment]
> The big advantage of the link I provided is that it produces a 3d object with UV coordinates, and it does it in OBJ format. It also has a few adjustment parameters that could be useful if you don't use a 3d app after (I had to because I wanted to export an FBX for a specific engine). But other than that the 3d photo inpainting algo you adapted for windows should provide better 3d results in my opinion. The inpainting should make a difference.
> 
> Also, after testing multiple algorythms, I feel that LeRes is best for things like normal maps where local details are more important, and that for 3d extraction where accurate distances are important, Midas-21 in multi-resolution mode provides the best results. I'll keep on testing as this is all quite preliminary.

This sounds professional, I am just a newbie in 3D modeling, so seems I have much to learn! Thanks for sharing!

> Testing an HTML embedding of a 3d model to see it it works (if it's a problem just delete - this is not important)
> 
> https://meshvalley.com/embed/6391b4d1fb93daaa5e90289a?play&nofx

I can see 'The Mask' here. LOL

**Comment by donlinglok1** [comment]
> Testing an HTML embedding of a 3d model to see it it works (if it's a problem just delete - this is not important)
> 
> https://meshvalley.com/embed/6391b4d1fb93daaa5e90289a?play&nofx


https://make3d.app/?ref=theresanaiforthat
@AugmentedRealityCat this one are similar and fast

**Comment by AugmentedRealityCat** [comment]
> https://make3d.app/?ref=theresanaiforthat @AugmentedRealityCat this one are similar and fast

This is extremely slow - I suppose it runs on the CPU, else there must be something wrong as I'm still waiting for the first image to process.

My current workflow is to use the DepthMap extension for Automatic1111 and to import the resulting depthmap into C4d to drive a polygon displacement effect. This is almost instant: it takes a few seconds to load and interpret a new depthmap, but you have to render those depthmaps in A1111 first.

**Comment by donlinglok1** [comment]
> > https://make3d.app/?ref=theresanaiforthat @AugmentedRealityCat this one are similar and fast
> 
> This is extremely slow - I suppose it runs on the CPU, else there must be something wrong as I'm still waiting for the first image to process.
> 
> My current workflow is to use the DepthMap extension for Automatic1111 and to import the resulting depthmap into C4d to drive a polygon displacement effect. This is almost instant: it takes a few seconds to load and interpret a new depthmap, but you have to render those depthmaps in A1111 first.

i see, i still don't have time to try on the new extension nearly updated, but it seems good base on your experience👍

**Comment by AugmentedRealityCat** [comment]
In fact, this is with the previous version of the extension - just plain depthmap based displacement, not actual 3d-inpainting. I have not had the time to test the latest version either ! Hopefully I'll get to do that over the weekend.

**Pull request merged**
